### ISSUE TITLE
Could you add a license file to root?

### ISSUE THREAD

**Issue by Pashokus** [grncdr/pct-encode#2]

**Comment by odzb** [comment]
This is a serious issue, unfortunately. We use a module which uses this module, and because of pct-encode's missing LICENSE file we have to search for a replacement for the module that includes it. And no, we can't just go to http://opensource.org/licenses/BSD-2-Clause and copy the text, because the <OWNER> and <YEAR> fields must be filled by the author.

**Comment by grncdr** [comment]
Released in 1.0.2
